#pragma once

#include "../types/SocketPrimitives.h"

struct CBLoginReq {
    SocketVarInt MessageID; // Generated by the server - should be unique to the connection.
    SocketIdentifier Channel; // Name of the plugin channel used to send the data
    uint32_t DataLength;
    std::unique_ptr<char[]> Data; // Any data, depending on the channel. The length of this array must be inferred from the packet length.

    friend SocketOStream& operator<<(SocketOStream& sock, const CBLoginReq& out) {
        sock << out.MessageID << out.Channel;
        sock.Write(out.Data.get(), out.DataLength);
        return sock;
    }
};